version: '3.6'
volumes:
        certs-volume:
                driver_opts:
                        type: "none"
                        device: "/<path>/"
                        o: "bind"
        conf-volume:
                driver_opts:
                        type: "none"
                        device: "/<path>/"
                        o: "bind"
        backup-data-volume:
                driver_opts:
                        type: "none"
                        device: "/<path>/"
                        o: "bind"
services:
        sshbackupserver:
                image: "jjoshtech/sshbackupserver"
                container_name: "sshbackupserver"
                hostname: "sshbackupserver"
                ports:
                  - "<PORT>:22"
                volumes:
                  - "certs-volume:/root/.ssh/"
                  - "conf-volume:/etc/ssh/"
                  - "backup-data-volume:/var/backup/"
                restart: "unless-stopped"
